export type CentralMember = {
  name: string;
  role: string;
  group: string;
  phone?: string;
  email?: string;
  photo?: string;
  photoScale?: number;
  photoPosition?: string;
  photoOrigin?: string;
  directionLogo?: string;
  directionLogoStyle?: 'corner' | 'pattern';
};

export const centralMembers: CentralMember[] = [
  // ─── Наблюдательный совет ───────────────────────────────────────────────
  {
    name: "Киселёв Михаил Сергеевич",
    role: "Председатель Наблюдательного совета РСО",
    group: "Наблюдательный совет",
    phone: "",
    email: "",
    photo: "/structure-safe/photo-01.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },

  // ─── Правление ──────────────────────────────────────────────────────────
  {
    name: "Дрожжина Юлия Дмитриевна",
    role: "Председатель Правления РСО",
    group: "Правление",
    phone: "",
    email: "",
    photo: "/structure-safe/photo-02.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },

  // ─── Руководство Центрального штаба ─────────────────────────────────────
  {
    name: "Зубащенко Ярослав Викторович",
    role: "Командир ЦШ МООО «РСО»",
    group: "Руководство Центрального штаба",
    phone: "8-903-025-40-10, @yaroslav_zubashchenko",
    email: "",
    photo: "/structure-safe/photo-03.jpg",
    directionLogo: "/svg/directions/zubashchenko-logo.svg",
    directionLogoStyle: "corner",
  },
  {
    name: "Позднякова Юлия Евгеньевна",
    role: "Комиссар ЦШ МООО «РСО»",
    group: "Руководство Центрального штаба",
    phone: "8-913-635-25-29, @yulyapozdno",
    email: "",
    photo: "/structure-safe/photo-04.jpg",
    directionLogo: "/svg/directions/pozdnyakova-logo.svg",
    directionLogoStyle: "pattern",
  },

  // ─── Руководители направлений ────────────────────────────────────────────
  {
    name: "Коротков Дмитрий Олегович",
    role: "Руководитель направления СОП ЦШ МООО «РСО»",
    group: "Руководители направлений",
    phone: "8-961-880-99-55, @celyimir",
    email: "",
    photo: "/structure-safe/photo-05.jpg",
    directionLogo: "/svg/directions/sop-color.svg",
  },
  {
    name: "Шалыгин Андрей Викторович",
    role: "Руководитель направления ССО ЦШ МООО «РСО»",
    group: "Руководители направлений",
    phone: "8-999-469-18-05, @AndreyShV",
    email: "",
    photo: "/structure-safe/photo-06.jpg",
    directionLogo: "/svg/directions/construction-color.svg",
  },
  {
    name: "Блюмин Алексей Александрович",
    role: "Руководитель направления ССхО ЦШ МООО «РСО»",
    group: "Руководители направлений",
    phone: "8-906-887-55-63, @aablumin",
    email: "",
    photo: "/structure-safe/photo-07.jpg",
    directionLogo: "/svg/directions/agriculture-color.svg",
  },
  {
    name: "Шайкин Павел Александрович",
    role: "Руководитель направления СПуО ЦШ МООО «РСО»",
    group: "Руководители направлений",
    phone: "8-914-197-93-56, @Shaikin_Pavel",
    email: "",
    photo: "/structure-safe/photo-08.png",
    directionLogo: "/svg/directions/puting-color.svg",
  },
  {
    name: "Живой Владимир Андреевич",
    role: "Заместитель руководителя направления ССхО ЦШ МООО «РСО»",
    group: "Руководители направлений",
    phone: "8-918-546-32-68, @volodiyay",
    email: "",
    photo: "/structure-safe/photo-09.png",
    directionLogo: "/svg/directions/agriculture-color.svg",
  },
  {
    name: "Грязнова Екатерина Александровна",
    role: "Руководитель направления ССервО ЦШ МООО «РСО»",
    group: "Руководители направлений",
    phone: "8-952-805-05-80, @grznv_k",
    email: "",
    photo: "/structure-safe/photo-10.jpg",
    directionLogo: "/svg/directions/service-color.svg",
  },
  {
    name: "Комарова Полина Евгеньевна",
    role: "Руководитель направления СПО МООО «РСО»",
    group: "Руководители направлений",
    phone: "8-908-794-10-76, @polina423",
    email: "",
    photo: "/structure-safe/photo-11.jpg",
    directionLogo: "/svg/directions/pedagogy-color.svg",
  },
  {
    name: "Рыбакова Маргарита Николаевна",
    role: "Руководитель направления ТОП ЦШ МООО «РСО»",
    group: "Руководители направлений",
    phone: "8-960-303-56-22, @immortallem",
    email: "",
    photo: "/structure-safe/photo-12.jpg",
    directionLogo: "/svg/directions/youth-color.svg",
  },
  {
    name: "Сальникова Ирина Андреевна",
    role: "Руководитель направления СМО ЦШ МООО «РСО»",
    group: "Руководители направлений",
    phone: "8-909-517-34-37, @iraidandko",
    email: "",
    photo: "/structure-safe/photo-13.png",
    directionLogo: "/svg/directions/medical-color.svg",
  },
  {
    name: "Пасенкова Варвара Николаевна",
    role: "Руководитель направления студенческих отрядов железнодорожного транспорта МООО «РСО»",
    group: "Руководители направлений",
    phone: "8-999-459-87-74, @V_N_Pasenkova",
    email: "",
    photo: "/structure-safe/photo-14.jpg",
    directionLogo: "/svg/directions/railway-color.svg",
  },

  // ─── Аппарат МООО «РСО» ─────────────────────────────────────────────────
  {
    name: "Барсукова Маргарита Владимировна",
    role: "Руководитель Аппарата МООО «РСО»",
    group: "Аппарат МООО «РСО»",
    phone: "8-983-385-15-44, @MargaritaBars25",
    email: "",
    photo: "/structure-safe/photo-15.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Репп Владимир Александрович",
    role: "Заместитель Руководителя Аппарата МООО «РСО»",
    group: "Аппарат МООО «РСО»",
    phone: "8-962-330-20-11, @vrepp",
    email: "",
    photo: "/structure-safe/photo-16.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Пискарева Ксения Викторовна",
    role: "Руководитель направления международного сотрудничества и партнёрских программ ЦШ МООО «РСО»",
    group: "Аппарат МООО «РСО»",
    phone: "8-930-700-13-90, @kseniapiskareva",
    email: "",
    photo: "/structure-safe/photo-17.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Соколова Анастасия Игоревна",
    role: "Советник Руководителя (командира) Центрального штаба",
    group: "Аппарат МООО «РСО»",
    phone: "8-905-049-15-11, @ai_sokolova",
    email: "",
    photo: "/structure-safe/photo-18.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Алексенко Анна Викторовна",
    role: "Специалист Аппарата МООО «РСО»",
    group: "Аппарат МООО «РСО»",
    phone: "8-961-088-27-25, @aleksisss_a",
    email: "",
    photo: "/structure-safe/photo-19.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Стрелкова Анна Олеговна",
    role: "Специалист Аппарата МООО «РСО» (бухгалтер)",
    group: "Аппарат МООО «РСО»",
    phone: "8-951-191-51-72, @strelkovaan",
    email: "",
    photo: "/structure-safe/photo-20.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Зорина Мария Александровна",
    role: "Специалист Аппарата МООО «РСО»",
    group: "Аппарат МООО «РСО»",
    phone: "8-913-742-31-48, @maryzor99",
    email: "",
    photo: "/structure-safe/photo-21.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },

  // ─── Комиссарский отдел ──────────────────────────────────────────────────
  {
    name: "Бродягина Валентина Валерьевна",
    role: "Ведущий специалист Аппарата МООО «РСО»",
    group: "Комиссарский отдел",
    phone: "8-903-674-00-05, @brodygina",
    email: "",
    photo: "/structure-safe/photo-22.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Джанхотова Анна Васильевна",
    role: "Специалист Аппарата МООО «РСО»",
    group: "Комиссарский отдел",
    phone: "8-905-907-26-00, @dzhan97",
    email: "",
    photo: "/structure-safe/photo-23.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Громова Ирина Артёмовна",
    role: "Специалист Аппарата МООО «РСО»",
    group: "Комиссарский отдел",
    phone: "8-985-800-80-65, @irinagromoth",
    email: "",
    photo: "/structure-safe/photo-24.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Шахметов Ильяс Муратович",
    role: "Специалист Аппарата МООО «РСО»",
    group: "Комиссарский отдел",
    phone: "8-995-087-75-33, @shilmur",
    email: "",
    photo: "/structure-safe/photo-25.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Олейникова Анна Анатольевна",
    role: "Специалист Аппарата МООО «РСО»",
    group: "Комиссарский отдел",
    phone: "8-968-754-34-35, @anneoleynikova",
    email: "",
    photo: "/structure-safe/photo-26.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },

  // ─── PR-отдел ────────────────────────────────────────────────────────────
  {
    name: "Колачевская Божена Андреевна",
    role: "Руководитель PR-отдела МООО «РСО»",
    group: "PR-отдел",
    phone: "8-908-117-05-36, @Bozhena_Kolachevskaya",
    email: "",
    photo: "/structure-safe/photo-27.jpg",
    directionLogo: "/svg/directions/pr-color.svg",
  },
  {
    name: "Балбанова Альбина",
    role: "Специалист PR-отдела РСО, контент-менеджер социальных сетей МООО «РСО»",
    group: "PR-отдел",
    phone: "8-993-016-90-78, @aanidla",
    email: "",
    photo: "/structure-safe/photo-28.jpg",
    directionLogo: "/svg/directions/pr-color.svg",
  },
  {
    name: "Горлышкина Злата Юрьевна",
    role: "Специалист PR-отдела РСО, координатор медиапроектов МООО «РСО»",
    group: "PR-отдел",
    phone: "8-913-584-33-78, @Zlata_PR_RSO",
    email: "",
    photo: "/structure-safe/photo-29.jpg",
    directionLogo: "/svg/directions/pr-color.svg",
  },
  {
    name: "Лобойко Наталья Сергеевна",
    role: "Специалист PR-отдела РСО, ведущий райтер",
    group: "PR-отдел",
    phone: "8-981-458-12-11, @kiss_love_a_39",
    email: "",
    photo: "/structure-safe/photo-30.jpg",
    directionLogo: "/svg/directions/pr-color.svg",
  },
  {
    name: "Коротецкая Анастасия Дмитриевна",
    role: "Специалист PR-отдела РСО по строительному направлению, райтер",
    group: "PR-отдел",
    phone: "8-999-632-17-43, @nutty_shorty",
    email: "",
    photo: "/structure-safe/photo-31.jpg",
    directionLogo: "/svg/directions/pr-color.svg",
  },
  {
    name: "Дубровская Алина Олеговна",
    role: "Специалист PR-отдела РСО по взаимодействию с Холдингом «РЖД»",
    group: "PR-отдел",
    phone: "8-913-646-16-44, @alinabask",
    email: "",
    photo: "/structure-safe/photo-32.jpg",
    directionLogo: "/svg/directions/pr-color.svg",
  },
  {
    name: "Ситдиков Руслан Марсельевич",
    role: "Специалист PR-отдела РСО, дизайнер МООО «РСО»",
    group: "PR-отдел",
    phone: "8-909-440-00-83, @rusitdikov",
    email: "",
    photo: "/structure-safe/photo-33.jpg",
    directionLogo: "/svg/directions/pr-color.svg",
  },
  {
    name: "Приходько Максим Александрович",
    role: "Специалист PR-отдела РСО, дизайнер, SMM-менеджер канала MAX",
    group: "PR-отдел",
    phone: "8-953-391-63-77, @prhdk_m",
    email: "",
    photo: "/structure-safe/photo-34.jpg",
    directionLogo: "/svg/directions/pr-color.svg",
  },

  // ─── Отдел регионального развития ────────────────────────────────────────
  {
    name: "Стома Алина Андреевна",
    role: "Исполняющий обязанности руководителя отдела по взаимодействию и развитию регионов",
    group: "Отдел регионального развития",
    phone: "8-962-818-68-82, @alinastoma",
    email: "",
    photo: "/structure-safe/photo-35.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Косаржевский Александр Сергеевич",
    role: "Специалист отдела по взаимодействию и развитию регионов",
    group: "Отдел регионального развития",
    phone: "8-992-290-03-09, @ytuta2",
    email: "",
    photo: "/structure-safe/photo-36.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Малянова Анастасия Юрьевна",
    role: "Специалист отдела по взаимодействию и развитию регионов",
    group: "Отдел регионального развития",
    phone: "8-926-257-12-10, @anastasia_malianova",
    email: "",
    photo: "/structure-safe/photo-37.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Муругова Милана Романовна",
    role: "Специалист отдела по взаимодействию и развитию регионов",
    group: "Отдел регионального развития",
    phone: "8-967-761-21-94, @mln_mr",
    email: "",
    photo: "/structure-safe/photo-38.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Кубашева Татьяна Николаевна",
    role: "Специалист отдела по взаимодействию и развитию регионов",
    group: "Отдел регионального развития",
    phone: "8-912-767-10-32, @tatyanakubasheva",
    email: "",
    photo: "/structure-safe/photo-39.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },

  // ─── Отдел реализации мероприятий по профобучению ────────────────────────
  {
    name: "Яблокова Анна Владимировна",
    role: "Руководитель отдела реализации мероприятий по профобучению",
    group: "Отдел реализации мероприятий по профобучению",
    phone: "8-918-903-95-91, @Ane4ka_Yablokova",
    email: "",
    photo: "/structure-safe/photo-40.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Зверкова Елизавета Владимировна",
    role: "Ведущий специалист по организационно-техническому обеспечению предоставления грантов",
    group: "Отдел реализации мероприятий по профобучению",
    phone: "8-988-409-49-71, @ElizZver",
    email: "",
    photo: "/structure-safe/photo-41.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Зотова Наталия Викторовна",
    role: "Заместитель руководителя отдела реализации мероприятий по профобучению",
    group: "Отдел реализации мероприятий по профобучению",
    phone: "8-917-672-72-38, @Zotova_Natalia85",
    email: "",
    photo: "",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Рокина Анастасия Михайловна",
    role: "Ведущий специалист по казначескому сопровождению и обеспечению выплат",
    group: "Отдел реализации мероприятий по профобучению",
    phone: "8-914-725-35-46, @am_rokina",
    email: "",
    photo: "/structure-safe/photo-42.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Рочева Алена Дмитриевна",
    role: "Специалист отдела реализации мероприятий по профобучению",
    group: "Отдел реализации мероприятий по профобучению",
    phone: "8-912-155-86-63, @harizako",
    email: "",
    photo: "/structure-safe/photo-43.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Ровнина Анна Васильевна",
    role: "Специалист отдела реализации мероприятий по профобучению",
    group: "Отдел реализации мероприятий по профобучению",
    phone: "8-923-678-42-55, @AnnaRovnina",
    email: "",
    photo: "/structure-safe/photo-44.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Семеренко Анна Валерьевна",
    role: "Специалист отдела реализации мероприятий по профобучению",
    group: "Отдел реализации мероприятий по профобучению",
    phone: "8-913-657-81-87, @Semerenko_Anna",
    email: "",
    photo: "/structure-safe/photo-45.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Юрова Ольга Анатольевна",
    role: "Специалист отдела реализации мероприятий по профобучению",
    group: "Отдел реализации мероприятий по профобучению",
    phone: "8-918-602-14-07, @OlyaYurova",
    email: "",
    photo: "/structure-safe/photo-46.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Пажетных Алена Дмитриевна",
    role: "Специалист отдела реализации мероприятий по профобучению",
    group: "Отдел реализации мероприятий по профобучению",
    phone: "8-969-974-81-39, @AlenaPazhetnykh",
    email: "",
    photo: "/structure-safe/photo-47.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Ляхова Светлана Игоревна",
    role: "Специалист отдела реализации мероприятий по профобучению",
    group: "Отдел реализации мероприятий по профобучению",
    phone: "8-913-656-36-11, @VinnieKZ",
    email: "",
    photo: "/structure-safe/photo-48.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Фатыхова Дамира Ильфатовна",
    role: "Специалист отдела реализации мероприятий по профобучению",
    group: "Отдел реализации мероприятий по профобучению",
    phone: "8-927-422-51-09, @mira_fdi",
    email: "",
    photo: "/structure-safe/photo-49.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Давиденко Анастасия Юрьевна",
    role: "Методист отдела реализации мероприятий по профобучению",
    group: "Отдел реализации мероприятий по профобучению",
    phone: "8-910-357-32-44, @Anarusheva",
    email: "",
    photo: "/structure-safe/photo-50.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Анпилогова Валерия Евгеньевна",
    role: "Специалист отдела реализации мероприятий по профобучению",
    group: "Отдел реализации мероприятий по профобучению",
    phone: "8-988-534-04-53, @anpilogova_v",
    email: "",
    photo: "",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Филатова Диана Дмитриевна",
    role: "Методист отдела реализации мероприятий по профобучению",
    group: "Отдел реализации мероприятий по профобучению",
    phone: "8-950-856-58-69, @Dia_Dmi",
    email: "",
    photo: "",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Ислаев Константин Васильевич",
    role: "Специалист отдела реализации мероприятий по профобучению",
    group: "Отдел реализации мероприятий по профобучению",
    phone: "8-917-221-64-17, @I1KV1",
    email: "",
    photo: "/structure-safe/photo-51.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },

  // ─── АНО ДПО «РСО-Развитие» ─────────────────────────────────────────────
  {
    name: "Корнилова Мария Андреевна",
    role: "Директор АНО ДПО «РСО-РАЗВИТИЕ»",
    group: "АНО ДПО «РСО-Развитие»",
    phone: "8-912-747-45-30, @mariiakorn",
    email: "",
    photo: "/structure-safe/photo-52.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Меркулова Мария Вячеславовна",
    role: "Заместитель директора АНО ДПО «РСО-РАЗВИТИЕ»",
    group: "АНО ДПО «РСО-Развитие»",
    phone: "8-913-883-96-46",
    email: "",
    photo: "/structure-safe/photo-53.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Хмелевская Валерия Олеговна",
    role: "Куратор корпоративного университета АНО ДПО «РСО-Развитие»",
    group: "АНО ДПО «РСО-Развитие»",
    phone: "8-925-874-21-45, @kh_vlrshka",
    email: "",
    photo: "/structure-safe/photo-54.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Шамшина Виктория Сергеевна",
    role: "Бренд-менеджер ТрудКрутШопа (АНО ДПО РСО-РАЗВИТИЕ)",
    group: "АНО ДПО «РСО-Развитие»",
    phone: "8-902-909-21-74",
    email: "",
    photo: "/structure-safe/photo-55.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Дунаевская Полина Александровна",
    role: "Бренд-менеджер ТрудКрутШопа (АНО ДПО РСО-РАЗВИТИЕ)",
    group: "АНО ДПО «РСО-Развитие»",
    phone: "8-951-409-62-95",
    email: "",
    photo: "/structure-safe/photo-56.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Сидорова Алина Михайловна",
    role: "Руководитель отдела по созданию контента ДПО «РСО-Развитие», руководитель Лук продакшн",
    group: "АНО ДПО «РСО-Развитие»",
    phone: "8-968-416-90-08, @alina_bw",
    email: "",
    photo: "",
    directionLogo: "/svg/directions/default-logo.svg",
  },

  // ─── ООО «РСО Инжиниринг» ───────────────────────────────────────────────
  {
    name: "Потемин Евгений Александрович",
    role: "Генеральный директор ООО «РСО Инжиниринг»",
    group: "ООО «РСО Инжиниринг»",
    phone: "8-919-725-55-65, @Evgeniy_Potemin",
    email: "",
    photo: "/structure-safe/photo-57.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Заболотских Александр Владимирович",
    role: "Заместитель генерального директора ООО «РСО Инжиниринг»",
    group: "ООО «РСО Инжиниринг»",
    phone: "8-963-454-77-45, @Zabolotskikh_Aleksandr",
    email: "",
    photo: "/structure-safe/photo-58.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Азарченко Яна Андреевна",
    role: "Заместитель генерального директора по направлению HoReCa ООО «РСО Инжиниринг»",
    group: "ООО «РСО Инжиниринг»",
    phone: "8-919-685-96-90, @ozornayana",
    email: "",
    photo: "/structure-safe/photo-59.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Чичерова Ольга Александровна",
    role: "Руководитель отдела администрирования проектов ООО «РСО Инжиниринг»",
    group: "ООО «РСО Инжиниринг»",
    phone: "8-915-616-19-11, @chicherovao",
    email: "",
    photo: "/structure-safe/photo-60.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Орешкин Артем Александрович",
    role: "Руководитель отдела реализации проектов ООО «РСО Инжиниринг»",
    group: "ООО «РСО Инжиниринг»",
    phone: "8-912-681-00-85, @artemoresh",
    email: "",
    photo: "/structure-safe/photo-61.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Печникова Ксения Леонидовна",
    role: "Специалист по связям с общественностью ООО «РСО Инжиниринг»",
    group: "ООО «РСО Инжиниринг»",
    phone: "8-901-272-79-07, @xeniaoverdosse",
    email: "",
    photo: "/structure-safe/photo-62.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Олейник Эмиль Юрьевич",
    role: "Специалист ООО «РСО Инжиниринг» по HoReCa",
    group: "ООО «РСО Инжиниринг»",
    phone: "8-952-605-95-06",
    email: "",
    photo: "/structure-safe/photo-63.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
  {
    name: "Хаятова Алина Сергеевна",
    role: "Администратор проектов ООО «РСО Инжиниринг»",
    group: "ООО «РСО Инжиниринг»",
    phone: "8-909-089-02-08, @a_khayatova",
    email: "",
    photo: "/structure-safe/photo-64.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },

  // ─── Фонд поддержки движения ─────────────────────────────────────────────
  {
    name: "Юрченко Ксения Петровна",
    role: "Директор Фонда поддержки и развития движения студенческих отрядов",
    group: "Фонд поддержки движения",
    phone: "8-912-017-05-79, @travel_ksy",
    email: "",
    photo: "/structure-safe/photo-65.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },

  // ─── Кол-центр ───────────────────────────────────────────────────────────
  {
    name: "Короткова Анна Константиновна",
    role: "Руководитель кол-центра МООО «РСО»",
    group: "Кол-центр",
    phone: "8-913-144-36-35, @annakorotkova11076",
    email: "",
    photo: "/structure-safe/photo-66.jpg",
    directionLogo: "/svg/directions/default-logo.svg",
  },
];

export const centralGroupOrder = [
  "Наблюдательный совет",
  "Правление",
  "Руководство Центрального штаба",
  "Руководители направлений",
  "Аппарат МООО «РСО»",
  "Комиссарский отдел",
  "Отдел регионального развития",
  "PR-отдел",
  "Отдел реализации мероприятий по профобучению",
  "АНО ДПО «РСО-Развитие»",
  "ООО «РСО Инжиниринг»",
  "РСО Крым",
  "Фонд поддержки движения",
  "Кол-центр",
];
