export type PhotoPathMap = Record<string, string>;

export const photoPathMap: PhotoPathMap = {
  "/PR-отдел/А. А. Шабанова.jpg": "/structure-ascii/pr/.jpg",
  "/PR-отдел/А. Д. Коротецкая.JPG": "/structure-ascii/pr/jpg.jpg",
  "/PR-отдел/А. О. Дубровская.jpg": "/structure-ascii/pr/.jpg",
  "/PR-отдел/Б. А. Колачевская.jpg": "/structure-ascii/pr/.jpg",
  "/PR-отдел/З. Ю. Горлышкина.JPG": "/structure-ascii/pr/jpg.jpg",
  "/PR-отдел/Н.С. Лобойко.jpg": "/structure-ascii/pr/.jpg",
  "/PR-отдел/Р. М. Ситдиков.jpg": "/structure-ascii/pr/.jpg",
  "/Аппарат РСО/А. А. Олейникова.jpg": "/structure-ascii/.jpg",
  "/Аппарат РСО/А. И. Соколова.jpg": "/structure-ascii/.jpg",
  "/Аппарат РСО/А. О. Стрелкова.JPG": "/structure-ascii/jpg.jpg",
  "/Аппарат РСО/В. А. Репп.JPG": "/structure-ascii/jpg.jpg",
  "/Аппарат РСО/В. О. Хмелевская.JPG": "/structure-ascii/jpg.jpg",
  "/Аппарат РСО/К. В. Пискарева.jpg": "/structure-ascii/.jpg",
  "/Аппарат РСО/Э. К. Зяблицкая.JPG": "/structure-ascii/jpg.jpg",
  "/Комиссарский отдел РСО/А. В. Джанхотова.JPG": "/structure-ascii/jpg.jpg",
  "/Комиссарский отдел РСО/В. В. Бродягина.jpg": "/structure-ascii/.jpg",
  "/Комиссарский отдел РСО/И. А. Громова.JPG": "/structure-ascii/jpg.jpg",
  "/Комиссарский отдел РСО/Ю. Е. Позднякова.JPG": "/structure-ascii/jpg.jpg",
  "/М. С. Киселёв_Председатель Наблюдательного совета РСО.JPG": "/structure-ascii/jpg.jpg",
  "/Отдел профобучения РСО/А. В. Ровнина.jpg": "/structure-ascii/.jpg",
  "/Отдел профобучения РСО/А. В. Семеренко.jpg": "/structure-ascii/.jpg",
  "/Отдел профобучения РСО/А. В. Яблокова.jpg": "/structure-ascii/.jpg",
  "/Отдел профобучения РСО/А. Д. Пажетных.jpg": "/structure-ascii/.jpg",
  "/Отдел профобучения РСО/А. Д. Рочева.JPG": "/structure-ascii/jpg.jpg",
  "/Отдел профобучения РСО/А. М. Рокина.JPG": "/structure-ascii/jpg.jpg",
  "/Отдел профобучения РСО/А. Ю. Давиденко.jpg": "/structure-ascii/.jpg",
  "/Отдел профобучения РСО/Д. И. Фатыхова.JPG": "/structure-ascii/jpg.jpg",
  "/Отдел профобучения РСО/Е. В. Зверкова.JPG": "/structure-ascii/jpg.jpg",
  "/Отдел профобучения РСО/К. В. Ислаев.jpg": "/structure-ascii/.jpg",
  "/Отдел профобучения РСО/О. А. Юрова.jpg": "/structure-ascii/.jpg",
  "/Отдел профобучения РСО/С. И. Ляхова.jpg": "/structure-ascii/.jpg",
  "/Отдел регионального взаимодействия и развития/А. А. Стома.JPG": "/structure-ascii/jpg.jpg",
  "/Отдел регионального взаимодействия и развития/А. Ю. Малянова.JPG": "/structure-ascii/jpg.jpg",
  "/Отдел регионального взаимодействия и развития/М. В. Барсукова.JPG": "/structure-ascii/jpg.jpg",
  "/Отдел регионального взаимодействия и развития/Т. Н. Кубашева.JPG": "/structure-ascii/jpg.jpg",
  "/РСО Инжиниринг/А. А. Орешкин.jpg": "/structure-ascii/.jpg",
  "/РСО Инжиниринг/А. В. Заболотских.jpg": "/structure-ascii/.jpg",
  "/РСО Инжиниринг/А. И. Романчугов.jpg": "/structure-ascii/.jpg",
  "/РСО Инжиниринг/А. С. Хаятова.jpg": "/structure-ascii/.jpg",
  "/РСО Инжиниринг/Е. А. Потемин.jpg": "/structure-ascii/.jpg",
  "/РСО Инжиниринг/К. Л. Печникова.JPG": "/structure-ascii/jpg.jpg",
  "/РСО Инжиниринг/О. А. Чичерова.jpg": "/structure-ascii/.jpg",
  "/РСО Инжиниринг/Я. А. Азарченко.JPG": "/structure-ascii/jpg.jpg",
  "/РСО Развитие/А. А. Коротков.JPG": "/structure-ascii/jpg.jpg",
  "/РСО Развитие/Голубин Максим.JPG": "/structure-ascii/jpg.jpg",
  "/РСО Развитие/М. А. Корнилова.JPG": "/structure-ascii/jpg.jpg",
  "/РСО Развитие/П. Дунаевская.JPG": "/structure-ascii/jpg.jpg",
  "/Руководители направлений/А. А. Блюмин.jpg": "/structure-ascii/.jpg",
  "/Руководители направлений/А. В. Шалыгин.JPG": "/structure-ascii/jpg.jpg",
  "/Руководители направлений/В. А. Живой.PNG": "/structure-ascii/png.png",
  "/Руководители направлений/В. Н. Пасенкова.jpg": "/structure-ascii/.jpg",
  "/Руководители направлений/Д. О. Коротков.jpg": "/structure-ascii/.jpg",
  "/Руководители направлений/Е. А. Грязнова.JPG": "/structure-ascii/jpg.jpg",
  "/Руководители направлений/К. А. Сидорова.JPG": "/structure-ascii/jpg.jpg",
  "/Руководители направлений/М. Н. Рыбакова.JPG": "/structure-ascii/jpg.jpg",
  "/Руководители направлений/П. А. Шайкин.png": "/structure-ascii/.png",
  "/Руководители направлений/П. Е. Комарова.JPG": "/structure-ascii/jpg.jpg",
  "/Фонд поддержки и развития движения студенческих отрядов/К. П. Юрченко.JPG": "/structure-ascii/jpg.jpg",
  "/Ю. Е. Позднякова_Комиссар Центрального штаба Российских студенческих отрядов.JPG": "/structure-ascii/jpg.jpg",
  "/Ю. Н. Дрожжина__Председатель Правления РСО.jpg": "/structure-ascii/.jpg",
  "/Я. В. Зубащенко_Командир Центрального штаба Российских студенческих отрядов.jpg": "/structure-ascii/.jpg"
};
